from brian2.units import ms, mV, second, Hz
from .param_tools import *

sigv = 1./second

input_dict = {'T1': [1*second],
              'T2': [1*second],
              'T3': [5*second],
              'T4': [1*second],
              'syn_scl_rec' : [0],
              'syn_iscl_rec' : [0],
              'scl_rec_T' : [1*second],   
              'synEE_rec': [0],
              'synEI_rec': [0],
              'stdp_rec_T' : [1*second],
              'T5': [5*second],
              'crs_crrs_rec' : [0],
              'dt': [0.1*ms],
              'n_threads': [1],
              'N_e' : [400],
              'N_i' : [80],
              'syn_cond_mode' : ['biexp'],
              'syn_cond_mode_EI' : ['biexp'],
              'tau_e': [6*ms],
              'tau_i': [15*ms],
              'tau_e_rise': [3.75*ms],
              'tau_i_rise': [1.75*ms],
              'norm_f_EE': [2.75],
              'norm_f_EI': [2.5],
              'external_mode' : ['memnoise'],
              'mu_e' : [11.*mV],
              'mu_i' : [10.*mV],
              'sigma_e': [0.5**0.5*mV],
              'sigma_i': [0.5**0.5*mV],
              'a_EPoi': [0.005],
              'p_ee' : [0.15],
              'p_ei' : [0.5],
              'p_ie' : [0.15],
              'p_ii' : [0.5],
              
              'syn_noise' : [1],
              'syn_noise_type': ['kesten'],
              'syn_kesten_mu_epsilon_1':    [-.048/(60*second)],
              'syn_kesten_mu_eta':          [0.067/(60*second)],
              'syn_kesten_var_epsilon_1':   [0.015/(60*second)],
              'syn_kesten_var_eta':         [0.013/(60*second)],
              'syn_kesten_factor':          [300],
              'synEE_mod_dt' : [20*ms],
              
              'stdp_active': [1],
              'istdp_active': [1],
              'istdp_type' : ['sym'],
              'LTD_a' : [0.000005],
              'strct_active': [0],
              'istrct_active': [0],
              'memtraces_rec' : [1],
              'getraces_rec' : [1],
              'gitraces_rec' : [1],
              'nrec_GExc_stat': [400],
              'nrec_GInh_stat': [3],
              'GExc_stat_dt' : [2*ms],
              'GInh_stat_dt' : [2*ms],
              'synee_atraces_rec' : [1],
              'synee_activetraces_rec' : [0],
              'synee_Apretraces_rec': [0],
              'synee_Aposttraces_rec': [0],
              'n_synee_traces_rec': [1000],
              'synEE_stat_dt' : [2*ms],
              'synei_atraces_rec' : [1],
              'synei_activetraces_rec' : [0],
              'synei_Apretraces_rec': [0],
              'synei_Aposttraces_rec': [0],
              'n_synei_traces_rec': [1000],
              'synEI_stat_dt' : [2*ms],              
              'synee_a_nrecpoints': [10],
              'synei_a_nrecpoints': [10],
              'synEEdynrec': [1],
              'synEIdynrec': [1],
              'syndynrec_dt': [1*second],
              'syndynrec_npts': [10],
              'turnover_rec': [1],
              'strct_dt' : [1000*ms],
              'spks_rec' : [1],
              'T2_spks_rec': [0],
              'rates_rec': [1],
              'adjust_insertP': [0],
              'adjust_EI_insertP': [0],
              'csample_dt' : [10*second],
              'scl_active': [1],
              'iscl_active': [1],
              'dt_synEE_scaling': [1000*ms],
              'eta_scaling': [1.0],
              'amax': [2.0],
              'Aplus': [0.0015],
              'Aminus': [-0.00075],
              'a_distributed' : [1],
              'a_ee' : [0.002],
              'a_ie' : [0.002],
              'a_ei' : [0.002],
              'a_ii' : [0.002],
              'a_ie_mean' : [-1],
              'a_ii_mean' : [-1],
              'a_ie_sigma' : [1.4],
              'a_ii_sigma' : [1.4],
              'ATotalMax': [1.],#, 1.6/6, 1.8/6, 2.0/6],
              'iATotalMax': [0.7/6],#,1.0/6,1.2/6, 1.4/6, 1.6/6, 1.8/6],
              'ascale': [1.0],
              'Vt_distributed' : [1],
              'Vt_e' : [-50.*mV],
              'Vt_i' : [-51*mV],
              'Vt_e_sigma' : [0.1],
              'Vt_i_sigma' : [0.3],
              'random_seed' : [457]}


name = 'hdf5_data'
explore_dict = n_list(input_dict)

if __name__ == "__main__":
    print(name)
